plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'checkstyle' // Analisa más práticas de código
	id 'com.diffplug.spotless' version '6.25.0' // Formata o código automaticamente
}

group = 'com.wealthtrack'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'com.auth0:java-jwt:4.4.0'
	// Flyway Core e o suporte específico para PostgreSQL
	implementation 'org.flywaydb:flyway-core'
	implementation 'org.flywaydb:flyway-database-postgresql'
	// Firebase Admin SDK para Storage e Push Notifications
	implementation 'com.google.firebase:firebase-admin:9.2.0'
	// Biblioteca ultraleve para compressão e redimensionamento de imagens
	implementation 'net.coobird:thumbnailator:0.4.20'
	// RabbitMQ
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	// Kafka
	implementation 'org.springframework.kafka:spring-kafka'
	// Ably para WebSockets e Tempo Real
	implementation 'io.ably:ably-java:1.2.33'
	// Biblioteca do Spring AI (Usando o provedor Google Gemini)
	implementation 'org.springframework.ai:spring-ai-starter-model-google-genai'
	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
}

spotless {
	java {
		googleJavaFormat() // Adota o rigoroso padrão de formatação de código do Google
		removeUnusedImports() // Remove imports que não estão sendo usados
	}
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.ai:spring-ai-bom:1.1.0"
	}
}

tasks.register('preCommit') {
	group = 'verification'
	description = 'Formata o código e roda todos os testes e verificações antes de um commit'

	// Ordem de execução: 1. Formata, 2. Roda Linting (Checkstyle) e Testes
	dependsOn 'spotlessApply', 'check'
}

tasks.named('test') {
	useJUnitPlatform()
}
