spring.application.name=api
api.security.token.secret=${JWT_SECRET:chave-padrao-local-apenas-para-dev}

# Conexão com o Banco de Dados (Docker)
spring.datasource.url=jdbc:postgresql://localhost:5432/wealthtrack_db
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin_password_local}

# Desliga a criação automática de tabelas do Hibernate (O Flyway assume o controle)
spring.jpa.hibernate.ddl-auto=validate